azs:
- cloud_properties:
    availability_zone: nova
  name: z1
compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: minimal
  workers: 4

networks:
- name: default
  subnets:
  - azs:
    - z1
    range: 10.0.10.0/24
    reserved: [10.0.10.2-10.0.10.10]
    static: [10.0.10.11-10.0.10.30]
    gateway: 10.0.10.1
    cloud_properties:
      net_id: bc8559ef-b82d-4f03-b4f5-650e6d84add8
      security_groups: [bosh]
    dns:
    - 10.0.10.1
#  type: dynamic

- name: vip
  type: vip

vm_types:
- cloud_properties:
    instance_type: m1.medium
    root_disk_size_gb: 20
  name: minimal
- cloud_properties:
    instance_type: m1.medium
    root_disk_size_gb: 20
  name: small
- cloud_properties:
    instance_type: m1.large
    root_disk_size_gb: 100
  name: small-highmem

disk_types:
- name: 5120
  disk_size: 5120
- name: 10240
  disk_size: 10240

vm_extensions:
- name: kubo
  cloud_properties:
    security_groups: [bosh]
    loadbalancer_pools:
      - name: pool1
        port: 8443
